version: '3'

services:
  db-notes:
    container_name: notes-db
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notes
    ports:
      - 5432:5432
    expose: 
      - 5432
    command:
      -p 5432